fix cgroup2 mnt point issue on focal
vmtop was failing to run in cgroup2 focal based env
returning following error:

AttributeError: 'Machine' object has no attribute 'cpuset_mount_point'

Between bionic vs focal, cgroup2 when configured in unified mode,
mount point name is changed from cgroup to cgroup2 causing focal
based env with cgroup2 to not run.

This fixes it.